# Generated by Django 6.0.5 on 2026-05-28 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financiero', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaLargoPlazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la meta')),
                ('icono', models.CharField(choices=[('🏠', 'Vivienda'), ('✈️', 'Viaje'), ('💻', 'Tecnología'), ('🛡️', 'Fondo de Emergencia'), ('🎓', 'Educación'), ('🚗', 'Vehículo'), ('🎯', 'Otro')], default='🎯', max_length=10)),
                ('monto_objetivo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto objetivo (S/)')),
                ('monto_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto ahorrado (S/)')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_largo_plazo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta a Largo Plazo',
                'verbose_name_plural': 'Metas a Largo Plazo',
                'db_table': 'recomendaciones_metalargoplazoo',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MetaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(verbose_name='Período')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Meta de ahorro (S/)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_mensuales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta Mensual',
                'verbose_name_plural': 'Metas Mensuales',
                'ordering': ['-periodo'],
                'unique_together': {('usuario', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ahorro_actual', models.FloatField(verbose_name='Ahorro predicho (S/)')),
                ('meta_validada', models.FloatField(verbose_name='Meta validada (S/)')),
                ('gap', models.FloatField(verbose_name='Gap meta - ahorro (S/)')),
                ('cluster_id', models.IntegerField(verbose_name='ID cluster K-Means')),
                ('cluster_label', models.CharField(max_length=150, verbose_name='Etiqueta cluster')),
                ('confianza', models.CharField(max_length=250, verbose_name='Nivel de confianza')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recomendaciones.metamensual')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_ml', to='financiero.registromensual')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_ml', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado ML',
                'verbose_name_plural': 'Resultados ML',
                'ordering': ['-creado_en'],
            },
        ),
    ]
