# Generated by Django 6.0.5 on 2026-06-05 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSeleccionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(choices=[('Conservador', 'Conservador'), ('Balanceado', 'Balanceado'), ('Agresivo', 'Agresivo')], max_length=20)),
                ('ahorro_proyectado', models.FloatField(verbose_name='Ahorro proyectado (S/)')),
                ('meta_ahorro', models.FloatField(verbose_name='Meta de ahorro (S/)')),
                ('gastos_sugeridos', models.JSONField(help_text='Dict {GASTO_X: valor_optimizado} con los 8 gastos del plan')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_seleccion', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_seleccionados', to='recomendaciones.resultadoml')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_seleccionados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan Seleccionado',
                'verbose_name_plural': 'Planes Seleccionados',
                'ordering': ['-fecha_seleccion'],
            },
        ),
    ]
