# Generated by Django 6.0.5 on 2026-06-11 23:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0002_registromensual_bonif_monto'),
        ('recomendaciones', '0002_plan_seleccionado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='planseleccionado',
            index=models.Index(fields=['usuario', 'activo'], name='idx_plansel_user_activo'),
        ),
        migrations.AddIndex(
            model_name='resultadoml',
            index=models.Index(fields=['usuario', '-creado_en'], name='idx_resml_user_fecha'),
        ),
        migrations.AddIndex(
            model_name='resultadoml',
            index=models.Index(fields=['cluster_label'], name='idx_resml_cluster'),
        ),
        migrations.AddConstraint(
            model_name='planseleccionado',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('usuario',), name='unico_plan_activo_por_usuario'),
        ),
        migrations.AlterModelTable(
            name='metalargoplazo',
            table='recomendaciones_metalargoplazo',
        ),
    ]
