# Generated by Django 6.0.5 on 2026-06-20 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0002_registromensual_bonif_monto'),
        ('recomendaciones', '0003_planseleccionado_idx_plansel_user_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resultadoml',
            name='idx_resml_cluster',
        ),
        migrations.AddField(
            model_name='resultadoml',
            name='clase_predicha',
            field=models.IntegerField(default=0, verbose_name='Clase (0=Déficit, 1=Ahorra)'),
        ),
        migrations.AddField(
            model_name='resultadoml',
            name='label_predicha',
            field=models.CharField(default='', max_length=20, verbose_name='Etiqueta clase'),
        ),
        migrations.AddField(
            model_name='resultadoml',
            name='mes_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_referencia', to='financiero.registromensual', verbose_name='Mes de referencia'),
        ),
        migrations.AddField(
            model_name='resultadoml',
            name='necesita_recortar',
            field=models.FloatField(default=0.0, verbose_name='Falta recortar (S/)'),
        ),
        migrations.AddField(
            model_name='resultadoml',
            name='prob_ahorra',
            field=models.FloatField(default=0.0, verbose_name='Probabilidad de Ahorrar'),
        ),
        migrations.AddField(
            model_name='resultadoml',
            name='shap_top_features',
            field=models.JSONField(default=list, verbose_name='Top features SHAP'),
        ),
        migrations.AlterField(
            model_name='planseleccionado',
            name='nombre_plan',
            field=models.CharField(choices=[('Suave', 'Suave'), ('Equilibrado', 'Equilibrado'), ('Decidido', 'Decidido')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resultadoml',
            name='ahorro_actual',
            field=models.FloatField(verbose_name='Ahorro real (S/)'),
        ),
        migrations.AddIndex(
            model_name='resultadoml',
            index=models.Index(fields=['label_predicha'], name='idx_resml_clase'),
        ),
        migrations.RemoveField(
            model_name='resultadoml',
            name='cluster_id',
        ),
        migrations.RemoveField(
            model_name='resultadoml',
            name='cluster_label',
        ),
        migrations.RemoveField(
            model_name='resultadoml',
            name='gap',
        ),
    ]
