# Generated by Django 6.0.5 on 2026-07-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendaciones', '0004_remove_resultadoml_idx_resml_cluster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoml',
            name='categoria_objetivo',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Categoría de gasto priorizada'),
        ),
        migrations.AddField(
            model_name='resultadoml',
            name='escenario',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Escenario del plan'),
        ),
    ]
