# Generated by Django 6.0.5 on 2026-07-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendaciones', '0005_resultadoml_categoria_objetivo_resultadoml_escenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='planseleccionado',
            name='aviso_descartado',
            field=models.BooleanField(default=False, verbose_name='Aviso de plan desactualizado descartado'),
        ),
    ]
