# Generated by Django 6.0.5 on 2026-08-02 18:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendaciones', '0006_planseleccionado_aviso_descartado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metalargoplazo',
            name='monto_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='El monto ahorrado no puede ser negativo.')], verbose_name='Monto ahorrado (S/)'),
        ),
        migrations.AlterField(
            model_name='metalargoplazo',
            name='monto_objetivo',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='El monto objetivo debe ser mayor a S/ 0.')], verbose_name='Monto objetivo (S/)'),
        ),
    ]
