# Generated by Django 6.0.5 on 2026-09-06 16:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0003_alter_registromensual_bonif_monto_and_more'),
        ('recomendaciones', '0007_alter_metalargoplazo_monto_actual_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AporteMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='El aporte debe ser mayor a S/ 0.')], verbose_name='Monto aportado (S/)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='recomendaciones.metalargoplazo')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes_meta', to='financiero.registromensual')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes_meta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aporte a Meta',
                'verbose_name_plural': 'Aportes a Metas',
                'db_table': 'recomendaciones_aportemeta',
                'ordering': ['-creado_en'],
            },
        ),
    ]
