# Generated by Django 6.0.5 on 2026-09-17 20:17

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Requerido para el análisis ML.', null=True, validators=[django.core.validators.MinValueValidator(18, message='Debes ser mayor de edad (18 años o más) para registrarte.')], verbose_name='Edad (años)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[accounts.validators.validar_dominio_email], verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nickname',
            field=models.CharField(help_text='Nombre de usuario visible. Entre 3 y 20 caracteres, con al menos una letra.', max_length=30, unique=True, validators=[accounts.validators.validar_formato_nickname], verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 9 dígitos numéricos (ej: 987654321).', regex='^\\d{9}$')], verbose_name='Teléfono'),
        ),
    ]
