# Generated by Django 6.0.5 on 2026-09-18 03:44

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usuario_edad_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(blank=True, default='Lima', max_length=100, validators=[accounts.validators.validar_ciudad], verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='miembros_hogar',
            field=models.PositiveSmallIntegerField(default=1, help_text='Requerido para el análisis ML.', validators=[django.core.validators.MinValueValidator(1, message='El hogar debe tener al menos 1 miembro (tú mismo).'), django.core.validators.MaxValueValidator(20, message='Ingresa un número de miembros del hogar válido.')], verbose_name='Miembros del hogar'),
        ),
    ]
