# Generated by Django 6.0.5 on 2026-09-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usuario_ciudad_alter_usuario_miembros_hogar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='recordatorio_semanal_activo',
            field=models.BooleanField(default=False, help_text='Recibe un correo si no registraste tus ingresos/gastos esa semana.', verbose_name='Recordatorio semanal por correo'),
        ),
    ]
