# Generated by Django 6.0.5 on 2026-09-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usuario_recordatorio_semanal_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='registros_voz',
            field=models.PositiveIntegerField(default=0, help_text='Cuántas veces confirmó un registro dictado (logros Manos Libres / Asistente Fiel).', verbose_name='Registros hechos por voz'),
        ),
    ]
