# Generated by Django 6.0.5 on 2026-05-28 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(verbose_name='Período (mes)')),
                ('ing_planilla', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ingreso en planilla (S/)')),
                ('ing_informal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ingreso informal (S/)')),
                ('gasto_alimentos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Alimentos (S/)')),
                ('gasto_vestido', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vestido (S/)')),
                ('gasto_vivienda_servicios', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vivienda y servicios (S/)')),
                ('gasto_salud', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salud (S/)')),
                ('gasto_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Transporte (S/)')),
                ('gasto_comunicaciones', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comunicaciones (S/)')),
                ('gasto_educacion', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Educación (S/)')),
                ('gasto_otros_bienes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Otros bienes (S/)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Mensual',
                'verbose_name_plural': 'Registros Mensuales',
                'ordering': ['-periodo'],
                'unique_together': {('usuario', 'periodo')},
            },
        ),
    ]
