# Generated by Django 6.0.5 on 2026-06-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromensual',
            name='bonif_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bonificación (CTS, gratificación, etc.) (S/)'),
        ),
    ]
