# Generated by Django 6.0.5 on 2026-08-02 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0002_registromensual_bonif_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromensual',
            name='bonif_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El monto no puede ser negativo.')], verbose_name='Bonificación (CTS, gratificación, etc.) (S/)'),
        ),
        migrations.AlterField(
            model_name='registromensual',
            name='gasto_alimentos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El monto no puede ser negativo.')], verbose_name='Alimentos (S/)'),
        ),
        migrations.AlterField(
            model_name='registromensual',
            name='gasto_comunicaciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El monto no puede ser negativo.')], verbose_name='Comunicaciones (S/)'),
        ),
        migrations.AlterField(
            model_name='registromensual',
            name='gasto_educacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El monto no puede ser negativo.')], verbose_name='Educación (S/)'),
        ),
        migrations.AlterField(
            model_name='registromensual',
            name='gasto_otros_bienes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El monto no puede ser negativo.')], verbose_name='Otros bienes (S/)'),
        ),
        migrations.AlterField(
            model_name='registromensual',
            name='gasto_salud',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El monto no puede ser negativo.')], verbose_name='Salud (S/)'),
        ),
        migrations.AlterField(
            model_name='registromensual',
            name='gasto_transporte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El monto no puede ser negativo.')], verbose_name='Transporte (S/)'),
        ),
        migrations.AlterField(
            model_name='registromensual',
            name='gasto_vestido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El monto no puede ser negativo.')], verbose_name='Vestido (S/)'),
        ),
        migrations.AlterField(
            model_name='registromensual',
            name='gasto_vivienda_servicios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El monto no puede ser negativo.')], verbose_name='Vivienda y servicios (S/)'),
        ),
        migrations.AlterField(
            model_name='registromensual',
            name='ing_informal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El monto no puede ser negativo.')], verbose_name='Ingreso informal (S/)'),
        ),
        migrations.AlterField(
            model_name='registromensual',
            name='ing_planilla',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El monto no puede ser negativo.')], verbose_name='Ingreso en planilla (S/)'),
        ),
    ]
