# Generated by Django 6.0.5 on 2026-06-11 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacion', '0003_seed_logros'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logrousuario',
            table='gamificacion_logrousuario',
        ),
    ]
