# Generated by Django 6.0.5 on 2026-05-28 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LOGIN_ADMIN', 'Inicio de sesión (admin)'), ('LOGOUT_ADMIN', 'Cierre de sesión (admin)'), ('CREAR_USUARIO', 'Crear usuario'), ('VER_USUARIO', 'Ver detalles de usuario'), ('ACTIVAR_USUARIO', 'Activar cuenta de usuario'), ('DESACTIVAR_USUARIO', 'Desactivar cuenta de usuario'), ('CAMBIAR_ROL', 'Cambiar rol de usuario'), ('EXPORTAR_DATOS', 'Exportar datos del sistema'), ('VER_ESTADISTICAS', 'Ver estadísticas del sistema')], max_length=30, verbose_name='Acción')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_admin', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
                ('usuario_objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario afectado')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha'],
            },
        ),
    ]
