# Generated by Django 6.0.5 on 2026-09-15 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0002_fix_ip_address'),
        ('recomendaciones', '0008_aportemeta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidacionPrimerUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(verbose_name='Período analizado')),
                ('clase_predicha', models.IntegerField(verbose_name='Clase predicha (0=Déficit, 1=Ahorra)')),
                ('prob_ahorra', models.FloatField(verbose_name='Probabilidad de Ahorrar')),
                ('confianza', models.CharField(max_length=20, verbose_name='Confianza')),
                ('ing_total', models.FloatField(verbose_name='Ingreso total (S/)')),
                ('gasto_total', models.FloatField(verbose_name='Gasto total (S/)')),
                ('ahorro_real', models.FloatField(verbose_name='Ahorro real (S/)')),
                ('clase_real', models.IntegerField(verbose_name='Clase real (0=Déficit, 1=Ahorra)')),
                ('tipo', models.CharField(choices=[('TP', 'Verdadero positivo'), ('FP', 'Falso positivo'), ('TN', 'Verdadero negativo'), ('FN', 'Falso negativo')], max_length=2, verbose_name='Resultado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validacion_primer_uso', to='recomendaciones.resultadoml', verbose_name='Análisis ML origen')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validacion_ml', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Validación ML (primer uso)',
                'verbose_name_plural': 'Validaciones ML (primer uso)',
                'ordering': ['-creado_en'],
            },
        ),
    ]
