# Generated by Django 6.0.5 on 2026-09-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0003_validacionprimeruso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='accion',
            field=models.CharField(choices=[('LOGIN_ADMIN', 'Inicio de sesión (admin)'), ('LOGOUT_ADMIN', 'Cierre de sesión (admin)'), ('CREAR_USUARIO', 'Crear usuario'), ('VER_USUARIO', 'Ver detalles de usuario'), ('ACTIVAR_USUARIO', 'Activar cuenta de usuario'), ('DESACTIVAR_USUARIO', 'Desactivar cuenta de usuario'), ('CAMBIAR_ROL', 'Cambiar rol de usuario'), ('EXPORTAR_DATOS', 'Exportar datos del sistema'), ('VER_ESTADISTICAS', 'Ver estadísticas del sistema'), ('ENVIAR_RECORDATORIOS', 'Enviar recordatorios semanales de registro')], max_length=30, verbose_name='Acción'),
        ),
    ]
